service: fgl-front-end
runtime: python27

api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: dist/index.html
  upload: dist/index.html
- url: /auth/.*
  static_files: dist/index.html
  upload: dist/index.html
- url: /e-commerce/.*
  static_files: dist/index.html
  upload: dist/index.html
- url: /
  static_dir: dist

skip_files:
  - e2e/
  - node_modules/
  - src/
  - coverage
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE

